language: objective-c
osx_image: xcode7.2
script:
  - xctool -workspace SidebarOverlay.xcworkspace -scheme SidebarOverlay -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace SidebarOverlay.xcworkspace -scheme SidebarOverlay -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f6539164e08e56cd75f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
