language: swift
osx_image: xcode7.2
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - xctool -workspace SidebarOverlay.xcworkspace -scheme SidebarOverlay -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace SidebarOverlay.xcworkspace -scheme SidebarOverlay -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
