language: objective-c
osx_image: xcode7.2b1
script:
  - xcodebuild -workspace SidebarOverlay.xcworkspace -scheme SidebarOverlay -sdk iphonesimulator clean build test -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f6539164e08e56cd75f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
